config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  # Login
  get  'login',  to: 'sessions#new', as: :login
  post 'login',  to: 'sessions#create', as: :create_session
  get  'logout', to: 'sessions#destroy', as: :logout

  # Signup
  get  'signup', to: 'signup#new', as: :new_signup
  post 'signup', to: 'signup#create', as: :signup

  # Edit account
  resource :account, only: [:show, :edit, :update]

  # Other users
  resources :users, only: [:index, :show] do
    get :follow, on: :member
    get :unfollow, on: :member

    get :block, on: :member
    get :unblock, on: :member
  end

  resources :messages, only: [:create]
end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :requester, class_name: 'User'
  belongs_to :blocked, class_name: 'User'
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :content
  validates_length_of :content, maximum: 255

  def self.feed_for_user(user, page = nil)
    messages = arel_table
    following = messages[:user_id].in(user.following_ids)
    self_messages = messages[:user_id].eq(user.id)
    where(following.or(self_messages)).page(page)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :name, :username, :email, :password

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :username, format: { with: /\A[a-z0-9_-]{3,25}\z/i }

  has_many :messages

  # Follows
  has_many :follow_relationships,   class_name: 'Follow', foreign_key: 'follower_id',
                                                          dependent: :destroy
  has_many :followed_relationships, class_name: 'Follow', foreign_key: 'follower_id',
                                                          dependent: :destroy
  has_many :followers, through: :followed_relationships 
  has_many :following, through: :follow_relationships, source: :followed

  # Blocks
  has_many :requested_blocks, class_name: 'Block', foreign_key: 'requester_id',
                                                          dependent: :destroy
  has_many :active_blocks,    class_name: 'Block', foreign_key: 'blocked_id',
                                                          dependent: :destroy

  has_many :blocked_by_users, through: :active_blocks, source: :requester
  has_many :blocked_users, through: :requested_blocks, source: :blocked

  scope :excluding_user, ->(user) { where.not(id: user.id) }

  def blocked?(user)
    blocked_users.include? user
  end

  def blocked_by?(user)
    blocked_by_users.include? user
  end

  def block(user)
    return false if self == user
    user.unfollow self
    requested_blocks.find_or_create_by(blocked_id: user.id)
  end

  def unblock(user)
    relation = requested_blocks.find_by(blocked_id: user.id)
    relation ? relation.destroy : false
  end

  def feed(page = nil)
    Message.feed_for_user(self, page)
  end

  def following?(user)
    following.include? user
  end

  def follow(user)
    return false if self == user || blocked_by?(user)
    follow_relationships.find_or_create_by(followed_id: user.id)
  end

  def unfollow(user)
    relation = followed_relationships.find_by(followed_id: user.id)
    relation ? relation.destroy : false
  end

  def to_param
    username
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authorize
  before_filter :load_user

  def update
    if @user.update_attributes(user_params)
      redirect_to account_path, notice: 'Your account have been successfully updated.'
    else
      render :edit
    end
  end

  private

  def load_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: 'Please login first' unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authorize

  def index
    @user = current_user
    @message = @user.messages.build
    @messages = @user.feed params[:page]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authorize

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path, notice: 'Your tweet have been published'
    else
      redirect_to root_path, alert: "Sorry, we are unable to post your tweet"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'

  def create
    user = User.find_by(username: user_params[:username])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You have been successfully logged in'
    else
      redirect_to login_path, alert: 'Invalid username or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'You have logged out successfully'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Your account have been successfully created'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  before_filter :load_user, except: :index
  before_filter :check_if_is_blocked, only: :show

  def index
    @users = User.excluding_user(current_user).page params[:page]
  end

  def show
    @messages = @user.messages.page params[:page]
  end

  def follow
    if current_user.follow(@user)
      redirect_to users_path, notice: "Now you are following #{@user.username}"
    else
      redirect_to users_path, notice: "You can't follow #{@user.username}"
    end
  end

  def unfollow
    if current_user.unfollow(@user)
      redirect_to users_path, notice: "You unfollowed #{@user.username}"
    else
      redirect_to users_path, notice: "You don't follow #{@user.username}"
    end
  end

  def block
    if current_user.block(@user)
      redirect_to users_path, notice: "You blocked #{@user.username}"
    else
      redirect_to users_path, notice: "You can't block #{@user.username}"
    end
  end

  def unblock
    if current_user.unblock(@user)
      redirect_to users_path, notice: "You unblocked #{@user.username}"
    else
      redirect_to users_path, notice: "You don't blocked #{@user.username}"
    end
  end

  private

  def load_user
    @user = User.find_by!(username: params[:id])
  end

  def check_if_is_blocked
    if @user.blocked? current_user
      redirect_to root_path, alert: 'This user is not avaliable'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_toggle_button(user)
    if current_user.following? user
      link_to 'Unfollow', unfollow_user_path(user), class: 'btn btn-danger'
    else
      link_to 'Follow', follow_user_path(user), class: 'btn btn-success'
    end
  end

  def block_toggle_button(user)
    if current_user.blocked? user
      link_to 'Unblock', unblock_user_path(user), class: 'btn btn-success'
    else
      link_to 'Block', block_user_path(user), class: 'btn btn-danger'
    end
  end
end

app/views/accounts/edit.html.erb
<%= form_for @user, url: account_path, html: { class: 'form-signin' } do |f| %>
  <h2 class="form-signin-heading">Edit your account</h2>

  <%= render 'shared/errors' %>

  <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

  <%= f.submit 'Update my account', class: 'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/accounts/show.html.erb
<h2>Your account</h2>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit my account', edit_account_path, class: 'btn btn-primary' %>

app/views/dashboard/index.html.erb
<%= content_for :title, 'Welcome' %>

<div class="row">
  <aside class="col-lg-4">
    <section>
      <h2><%= @user.name %></h2>
      <h4><%= @user.username %></h4>
    </section>
    <section>
      <%= form_for @message do |f| %>
        <%= f.text_area :content, class: 'form-control', placeholder: 'Your message' %>
        <%= f.submit 'Post', class: 'btn btn-primary' %>
      <% end %>
    </section>
  </aside>

  <div class="col-lg-8">
    <% if @messages.any? %>
      <h3>Messages</h3>
      <ol class="messages">
        <%= render @messages %>
      </ol>
      <%= paginate @messages %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twitterails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        </div>
      </div><!--/row-->
      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twitterails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body class="login">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        </div>
      </div><!--/row-->

      <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="content"><%= message.content %></span>
  <span class="timestamp">
    <%= time_ago_in_words(message.created_at) %> ago.
  </span>
</li>

app/views/shared/_errors.html.erb
<% @user.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Twitterails</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'My account', account_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/signup/new.html.erb
<%= form_for @user, url: signup_path, html: { class: 'form-signin' } do |f| %>
  <h2 class="form-signin-heading">Create your account</h2>

  <%= render 'errors' %>

  <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
  <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

  <%= f.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/users/_user.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail user-<%= user.id %>">
    <div class="caption">
      <h3><%= link_to user.name, user_path(user) %></h3>
      <p>@<%= user.username %><p>
      <p>
        <%= follow_toggle_button(user) %>
        <%= block_toggle_button(user) %>
      </p>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <%= render @users %>
</div>

<%= paginate @users %>

app/views/users/show.html.erb
<%= content_for :title, @user.username %>

<div class="row">
  <aside class="col-lg-4">
    <section>
      <h2><%= @user.name %></h2>
      <h4><%= @user.username %></h4>
      <%= follow_toggle_button(@user) %>
    </section>
  </aside>

  <div class="col-lg-8">
    <% if @messages.any? %>
      <h3>Messages</h3>
      <ol class="messages">
        <%= render @messages %>
      </ol>
      <%= paginate @messages %>
    <% else %>
      <p>This user don't have any messages yet</p>
    <% end %>
  </div>
</div>